name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - dask
  - distributed
  - dask-kubernetes
  - gcsfs
  - intake::intake-xarray
  - zarr
  # https://github.com/matplotlib/basemap/issues/435
  - matplotlib=3.0.0
  - cmocean
  - basemap
  - proj4
  - pyresample
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - ipywidgets
  - graphviz
  - nodejs
  - scipy
  - scikit-image
  - bokeh
  - pyviz/label/earthsim::holoviews
  - pyviz/label/earthsim::panel
  - geoviews
  - hvplot
  - rasterio
  - geoviews
  - datashader
  - gsw
  - julia
  - pip:
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/xgcm/xgcm.git
    - git+https://github.com/ContinuumIO/intake.git
    - kubernetes
    - graphviz
